// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: email.proto

package com.EmailSending.project;

public final class EmailOuterClass {
  private EmailOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NotificationsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Notifications)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string intervieweeName = 1;</code>
     */
    java.lang.String getIntervieweeName();
    /**
     * <code>string intervieweeName = 1;</code>
     */
    com.google.protobuf.ByteString
        getIntervieweeNameBytes();

    /**
     * <code>string ReceiverEmailId = 2;</code>
     */
    java.lang.String getReceiverEmailId();
    /**
     * <code>string ReceiverEmailId = 2;</code>
     */
    com.google.protobuf.ByteString
        getReceiverEmailIdBytes();

    /**
     * <code>string job_title = 3;</code>
     */
    java.lang.String getJobTitle();
    /**
     * <code>string job_title = 3;</code>
     */
    com.google.protobuf.ByteString
        getJobTitleBytes();

    /**
     * <pre>
     * string Subject =3;
     * string MessageText =4;
     * </pre>
     *
     * <code>string StartTime = 4;</code>
     */
    java.lang.String getStartTime();
    /**
     * <pre>
     * string Subject =3;
     * string MessageText =4;
     * </pre>
     *
     * <code>string StartTime = 4;</code>
     */
    com.google.protobuf.ByteString
        getStartTimeBytes();

    /**
     * <code>string EndTime = 5;</code>
     */
    java.lang.String getEndTime();
    /**
     * <code>string EndTime = 5;</code>
     */
    com.google.protobuf.ByteString
        getEndTimeBytes();

    /**
     * <code>string Date = 6;</code>
     */
    java.lang.String getDate();
    /**
     * <code>string Date = 6;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>string InterviewrName = 7;</code>
     */
    java.lang.String getInterviewrName();
    /**
     * <code>string InterviewrName = 7;</code>
     */
    com.google.protobuf.ByteString
        getInterviewrNameBytes();

    /**
     * <code>string meeting_invitation_link = 8;</code>
     */
    java.lang.String getMeetingInvitationLink();
    /**
     * <code>string meeting_invitation_link = 8;</code>
     */
    com.google.protobuf.ByteString
        getMeetingInvitationLinkBytes();
  }
  /**
   * Protobuf type {@code Notifications}
   */
  public  static final class Notifications extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Notifications)
      NotificationsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Notifications.newBuilder() to construct.
    private Notifications(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Notifications() {
      intervieweeName_ = "";
      receiverEmailId_ = "";
      jobTitle_ = "";
      startTime_ = "";
      endTime_ = "";
      date_ = "";
      interviewrName_ = "";
      meetingInvitationLink_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Notifications(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              intervieweeName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverEmailId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              jobTitle_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              startTime_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              endTime_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              date_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              interviewrName_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              meetingInvitationLink_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.EmailSending.project.EmailOuterClass.internal_static_Notifications_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.EmailSending.project.EmailOuterClass.internal_static_Notifications_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.EmailSending.project.EmailOuterClass.Notifications.class, com.EmailSending.project.EmailOuterClass.Notifications.Builder.class);
    }

    public static final int INTERVIEWEENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object intervieweeName_;
    /**
     * <code>string intervieweeName = 1;</code>
     */
    public java.lang.String getIntervieweeName() {
      java.lang.Object ref = intervieweeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        intervieweeName_ = s;
        return s;
      }
    }
    /**
     * <code>string intervieweeName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIntervieweeNameBytes() {
      java.lang.Object ref = intervieweeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        intervieweeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVEREMAILID_FIELD_NUMBER = 2;
    private volatile java.lang.Object receiverEmailId_;
    /**
     * <code>string ReceiverEmailId = 2;</code>
     */
    public java.lang.String getReceiverEmailId() {
      java.lang.Object ref = receiverEmailId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverEmailId_ = s;
        return s;
      }
    }
    /**
     * <code>string ReceiverEmailId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverEmailIdBytes() {
      java.lang.Object ref = receiverEmailId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverEmailId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JOB_TITLE_FIELD_NUMBER = 3;
    private volatile java.lang.Object jobTitle_;
    /**
     * <code>string job_title = 3;</code>
     */
    public java.lang.String getJobTitle() {
      java.lang.Object ref = jobTitle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobTitle_ = s;
        return s;
      }
    }
    /**
     * <code>string job_title = 3;</code>
     */
    public com.google.protobuf.ByteString
        getJobTitleBytes() {
      java.lang.Object ref = jobTitle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTTIME_FIELD_NUMBER = 4;
    private volatile java.lang.Object startTime_;
    /**
     * <pre>
     * string Subject =3;
     * string MessageText =4;
     * </pre>
     *
     * <code>string StartTime = 4;</code>
     */
    public java.lang.String getStartTime() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startTime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * string Subject =3;
     * string MessageText =4;
     * </pre>
     *
     * <code>string StartTime = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStartTimeBytes() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDTIME_FIELD_NUMBER = 5;
    private volatile java.lang.Object endTime_;
    /**
     * <code>string EndTime = 5;</code>
     */
    public java.lang.String getEndTime() {
      java.lang.Object ref = endTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endTime_ = s;
        return s;
      }
    }
    /**
     * <code>string EndTime = 5;</code>
     */
    public com.google.protobuf.ByteString
        getEndTimeBytes() {
      java.lang.Object ref = endTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATE_FIELD_NUMBER = 6;
    private volatile java.lang.Object date_;
    /**
     * <code>string Date = 6;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string Date = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTERVIEWRNAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object interviewrName_;
    /**
     * <code>string InterviewrName = 7;</code>
     */
    public java.lang.String getInterviewrName() {
      java.lang.Object ref = interviewrName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interviewrName_ = s;
        return s;
      }
    }
    /**
     * <code>string InterviewrName = 7;</code>
     */
    public com.google.protobuf.ByteString
        getInterviewrNameBytes() {
      java.lang.Object ref = interviewrName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interviewrName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEETING_INVITATION_LINK_FIELD_NUMBER = 8;
    private volatile java.lang.Object meetingInvitationLink_;
    /**
     * <code>string meeting_invitation_link = 8;</code>
     */
    public java.lang.String getMeetingInvitationLink() {
      java.lang.Object ref = meetingInvitationLink_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        meetingInvitationLink_ = s;
        return s;
      }
    }
    /**
     * <code>string meeting_invitation_link = 8;</code>
     */
    public com.google.protobuf.ByteString
        getMeetingInvitationLinkBytes() {
      java.lang.Object ref = meetingInvitationLink_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        meetingInvitationLink_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIntervieweeNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, intervieweeName_);
      }
      if (!getReceiverEmailIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, receiverEmailId_);
      }
      if (!getJobTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, jobTitle_);
      }
      if (!getStartTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, startTime_);
      }
      if (!getEndTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, endTime_);
      }
      if (!getDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, date_);
      }
      if (!getInterviewrNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, interviewrName_);
      }
      if (!getMeetingInvitationLinkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, meetingInvitationLink_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIntervieweeNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, intervieweeName_);
      }
      if (!getReceiverEmailIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, receiverEmailId_);
      }
      if (!getJobTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, jobTitle_);
      }
      if (!getStartTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, startTime_);
      }
      if (!getEndTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, endTime_);
      }
      if (!getDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, date_);
      }
      if (!getInterviewrNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, interviewrName_);
      }
      if (!getMeetingInvitationLinkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, meetingInvitationLink_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.EmailSending.project.EmailOuterClass.Notifications)) {
        return super.equals(obj);
      }
      com.EmailSending.project.EmailOuterClass.Notifications other = (com.EmailSending.project.EmailOuterClass.Notifications) obj;

      boolean result = true;
      result = result && getIntervieweeName()
          .equals(other.getIntervieweeName());
      result = result && getReceiverEmailId()
          .equals(other.getReceiverEmailId());
      result = result && getJobTitle()
          .equals(other.getJobTitle());
      result = result && getStartTime()
          .equals(other.getStartTime());
      result = result && getEndTime()
          .equals(other.getEndTime());
      result = result && getDate()
          .equals(other.getDate());
      result = result && getInterviewrName()
          .equals(other.getInterviewrName());
      result = result && getMeetingInvitationLink()
          .equals(other.getMeetingInvitationLink());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INTERVIEWEENAME_FIELD_NUMBER;
      hash = (53 * hash) + getIntervieweeName().hashCode();
      hash = (37 * hash) + RECEIVEREMAILID_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverEmailId().hashCode();
      hash = (37 * hash) + JOB_TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getJobTitle().hashCode();
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + getStartTime().hashCode();
      hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + getEndTime().hashCode();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (37 * hash) + INTERVIEWRNAME_FIELD_NUMBER;
      hash = (53 * hash) + getInterviewrName().hashCode();
      hash = (37 * hash) + MEETING_INVITATION_LINK_FIELD_NUMBER;
      hash = (53 * hash) + getMeetingInvitationLink().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.EmailSending.project.EmailOuterClass.Notifications parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.EmailSending.project.EmailOuterClass.Notifications parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.EmailSending.project.EmailOuterClass.Notifications parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.EmailSending.project.EmailOuterClass.Notifications parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.EmailSending.project.EmailOuterClass.Notifications parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.EmailSending.project.EmailOuterClass.Notifications parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.EmailSending.project.EmailOuterClass.Notifications parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.EmailSending.project.EmailOuterClass.Notifications parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.EmailSending.project.EmailOuterClass.Notifications parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.EmailSending.project.EmailOuterClass.Notifications parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.EmailSending.project.EmailOuterClass.Notifications parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.EmailSending.project.EmailOuterClass.Notifications parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.EmailSending.project.EmailOuterClass.Notifications prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Notifications}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Notifications)
        com.EmailSending.project.EmailOuterClass.NotificationsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.EmailSending.project.EmailOuterClass.internal_static_Notifications_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.EmailSending.project.EmailOuterClass.internal_static_Notifications_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.EmailSending.project.EmailOuterClass.Notifications.class, com.EmailSending.project.EmailOuterClass.Notifications.Builder.class);
      }

      // Construct using com.EmailSending.project.EmailOuterClass.Notifications.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        intervieweeName_ = "";

        receiverEmailId_ = "";

        jobTitle_ = "";

        startTime_ = "";

        endTime_ = "";

        date_ = "";

        interviewrName_ = "";

        meetingInvitationLink_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.EmailSending.project.EmailOuterClass.internal_static_Notifications_descriptor;
      }

      @java.lang.Override
      public com.EmailSending.project.EmailOuterClass.Notifications getDefaultInstanceForType() {
        return com.EmailSending.project.EmailOuterClass.Notifications.getDefaultInstance();
      }

      @java.lang.Override
      public com.EmailSending.project.EmailOuterClass.Notifications build() {
        com.EmailSending.project.EmailOuterClass.Notifications result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.EmailSending.project.EmailOuterClass.Notifications buildPartial() {
        com.EmailSending.project.EmailOuterClass.Notifications result = new com.EmailSending.project.EmailOuterClass.Notifications(this);
        result.intervieweeName_ = intervieweeName_;
        result.receiverEmailId_ = receiverEmailId_;
        result.jobTitle_ = jobTitle_;
        result.startTime_ = startTime_;
        result.endTime_ = endTime_;
        result.date_ = date_;
        result.interviewrName_ = interviewrName_;
        result.meetingInvitationLink_ = meetingInvitationLink_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.EmailSending.project.EmailOuterClass.Notifications) {
          return mergeFrom((com.EmailSending.project.EmailOuterClass.Notifications)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.EmailSending.project.EmailOuterClass.Notifications other) {
        if (other == com.EmailSending.project.EmailOuterClass.Notifications.getDefaultInstance()) return this;
        if (!other.getIntervieweeName().isEmpty()) {
          intervieweeName_ = other.intervieweeName_;
          onChanged();
        }
        if (!other.getReceiverEmailId().isEmpty()) {
          receiverEmailId_ = other.receiverEmailId_;
          onChanged();
        }
        if (!other.getJobTitle().isEmpty()) {
          jobTitle_ = other.jobTitle_;
          onChanged();
        }
        if (!other.getStartTime().isEmpty()) {
          startTime_ = other.startTime_;
          onChanged();
        }
        if (!other.getEndTime().isEmpty()) {
          endTime_ = other.endTime_;
          onChanged();
        }
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          onChanged();
        }
        if (!other.getInterviewrName().isEmpty()) {
          interviewrName_ = other.interviewrName_;
          onChanged();
        }
        if (!other.getMeetingInvitationLink().isEmpty()) {
          meetingInvitationLink_ = other.meetingInvitationLink_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.EmailSending.project.EmailOuterClass.Notifications parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.EmailSending.project.EmailOuterClass.Notifications) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object intervieweeName_ = "";
      /**
       * <code>string intervieweeName = 1;</code>
       */
      public java.lang.String getIntervieweeName() {
        java.lang.Object ref = intervieweeName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          intervieweeName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string intervieweeName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIntervieweeNameBytes() {
        java.lang.Object ref = intervieweeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          intervieweeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string intervieweeName = 1;</code>
       */
      public Builder setIntervieweeName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        intervieweeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string intervieweeName = 1;</code>
       */
      public Builder clearIntervieweeName() {
        
        intervieweeName_ = getDefaultInstance().getIntervieweeName();
        onChanged();
        return this;
      }
      /**
       * <code>string intervieweeName = 1;</code>
       */
      public Builder setIntervieweeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        intervieweeName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverEmailId_ = "";
      /**
       * <code>string ReceiverEmailId = 2;</code>
       */
      public java.lang.String getReceiverEmailId() {
        java.lang.Object ref = receiverEmailId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverEmailId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ReceiverEmailId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverEmailIdBytes() {
        java.lang.Object ref = receiverEmailId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverEmailId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ReceiverEmailId = 2;</code>
       */
      public Builder setReceiverEmailId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverEmailId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ReceiverEmailId = 2;</code>
       */
      public Builder clearReceiverEmailId() {
        
        receiverEmailId_ = getDefaultInstance().getReceiverEmailId();
        onChanged();
        return this;
      }
      /**
       * <code>string ReceiverEmailId = 2;</code>
       */
      public Builder setReceiverEmailIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverEmailId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object jobTitle_ = "";
      /**
       * <code>string job_title = 3;</code>
       */
      public java.lang.String getJobTitle() {
        java.lang.Object ref = jobTitle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jobTitle_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string job_title = 3;</code>
       */
      public com.google.protobuf.ByteString
          getJobTitleBytes() {
        java.lang.Object ref = jobTitle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jobTitle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string job_title = 3;</code>
       */
      public Builder setJobTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jobTitle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string job_title = 3;</code>
       */
      public Builder clearJobTitle() {
        
        jobTitle_ = getDefaultInstance().getJobTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string job_title = 3;</code>
       */
      public Builder setJobTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jobTitle_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object startTime_ = "";
      /**
       * <pre>
       * string Subject =3;
       * string MessageText =4;
       * </pre>
       *
       * <code>string StartTime = 4;</code>
       */
      public java.lang.String getStartTime() {
        java.lang.Object ref = startTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          startTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * string Subject =3;
       * string MessageText =4;
       * </pre>
       *
       * <code>string StartTime = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStartTimeBytes() {
        java.lang.Object ref = startTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * string Subject =3;
       * string MessageText =4;
       * </pre>
       *
       * <code>string StartTime = 4;</code>
       */
      public Builder setStartTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * string Subject =3;
       * string MessageText =4;
       * </pre>
       *
       * <code>string StartTime = 4;</code>
       */
      public Builder clearStartTime() {
        
        startTime_ = getDefaultInstance().getStartTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * string Subject =3;
       * string MessageText =4;
       * </pre>
       *
       * <code>string StartTime = 4;</code>
       */
      public Builder setStartTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        startTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object endTime_ = "";
      /**
       * <code>string EndTime = 5;</code>
       */
      public java.lang.String getEndTime() {
        java.lang.Object ref = endTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          endTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string EndTime = 5;</code>
       */
      public com.google.protobuf.ByteString
          getEndTimeBytes() {
        java.lang.Object ref = endTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string EndTime = 5;</code>
       */
      public Builder setEndTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string EndTime = 5;</code>
       */
      public Builder clearEndTime() {
        
        endTime_ = getDefaultInstance().getEndTime();
        onChanged();
        return this;
      }
      /**
       * <code>string EndTime = 5;</code>
       */
      public Builder setEndTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        endTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>string Date = 6;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Date = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Date = 6;</code>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Date = 6;</code>
       */
      public Builder clearDate() {
        
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>string Date = 6;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        date_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object interviewrName_ = "";
      /**
       * <code>string InterviewrName = 7;</code>
       */
      public java.lang.String getInterviewrName() {
        java.lang.Object ref = interviewrName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          interviewrName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string InterviewrName = 7;</code>
       */
      public com.google.protobuf.ByteString
          getInterviewrNameBytes() {
        java.lang.Object ref = interviewrName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          interviewrName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string InterviewrName = 7;</code>
       */
      public Builder setInterviewrName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        interviewrName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string InterviewrName = 7;</code>
       */
      public Builder clearInterviewrName() {
        
        interviewrName_ = getDefaultInstance().getInterviewrName();
        onChanged();
        return this;
      }
      /**
       * <code>string InterviewrName = 7;</code>
       */
      public Builder setInterviewrNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        interviewrName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object meetingInvitationLink_ = "";
      /**
       * <code>string meeting_invitation_link = 8;</code>
       */
      public java.lang.String getMeetingInvitationLink() {
        java.lang.Object ref = meetingInvitationLink_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          meetingInvitationLink_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string meeting_invitation_link = 8;</code>
       */
      public com.google.protobuf.ByteString
          getMeetingInvitationLinkBytes() {
        java.lang.Object ref = meetingInvitationLink_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          meetingInvitationLink_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string meeting_invitation_link = 8;</code>
       */
      public Builder setMeetingInvitationLink(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        meetingInvitationLink_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string meeting_invitation_link = 8;</code>
       */
      public Builder clearMeetingInvitationLink() {
        
        meetingInvitationLink_ = getDefaultInstance().getMeetingInvitationLink();
        onChanged();
        return this;
      }
      /**
       * <code>string meeting_invitation_link = 8;</code>
       */
      public Builder setMeetingInvitationLinkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        meetingInvitationLink_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Notifications)
    }

    // @@protoc_insertion_point(class_scope:Notifications)
    private static final com.EmailSending.project.EmailOuterClass.Notifications DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.EmailSending.project.EmailOuterClass.Notifications();
    }

    public static com.EmailSending.project.EmailOuterClass.Notifications getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Notifications>
        PARSER = new com.google.protobuf.AbstractParser<Notifications>() {
      @java.lang.Override
      public Notifications parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Notifications(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Notifications> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Notifications> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.EmailSending.project.EmailOuterClass.Notifications getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface APIResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:APIResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string responseMessage = 1;</code>
     */
    java.lang.String getResponseMessage();
    /**
     * <code>string responseMessage = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseMessageBytes();

    /**
     * <code>int32 messageCode = 2;</code>
     */
    int getMessageCode();
  }
  /**
   * Protobuf type {@code APIResponse}
   */
  public  static final class APIResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:APIResponse)
      APIResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use APIResponse.newBuilder() to construct.
    private APIResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private APIResponse() {
      responseMessage_ = "";
      messageCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private APIResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              responseMessage_ = s;
              break;
            }
            case 16: {

              messageCode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.EmailSending.project.EmailOuterClass.internal_static_APIResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.EmailSending.project.EmailOuterClass.internal_static_APIResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.EmailSending.project.EmailOuterClass.APIResponse.class, com.EmailSending.project.EmailOuterClass.APIResponse.Builder.class);
    }

    public static final int RESPONSEMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object responseMessage_;
    /**
     * <code>string responseMessage = 1;</code>
     */
    public java.lang.String getResponseMessage() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string responseMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGECODE_FIELD_NUMBER = 2;
    private int messageCode_;
    /**
     * <code>int32 messageCode = 2;</code>
     */
    public int getMessageCode() {
      return messageCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponseMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responseMessage_);
      }
      if (messageCode_ != 0) {
        output.writeInt32(2, messageCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponseMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responseMessage_);
      }
      if (messageCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, messageCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.EmailSending.project.EmailOuterClass.APIResponse)) {
        return super.equals(obj);
      }
      com.EmailSending.project.EmailOuterClass.APIResponse other = (com.EmailSending.project.EmailOuterClass.APIResponse) obj;

      boolean result = true;
      result = result && getResponseMessage()
          .equals(other.getResponseMessage());
      result = result && (getMessageCode()
          == other.getMessageCode());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseMessage().hashCode();
      hash = (37 * hash) + MESSAGECODE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.EmailSending.project.EmailOuterClass.APIResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.EmailSending.project.EmailOuterClass.APIResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.EmailSending.project.EmailOuterClass.APIResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.EmailSending.project.EmailOuterClass.APIResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.EmailSending.project.EmailOuterClass.APIResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.EmailSending.project.EmailOuterClass.APIResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.EmailSending.project.EmailOuterClass.APIResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.EmailSending.project.EmailOuterClass.APIResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.EmailSending.project.EmailOuterClass.APIResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.EmailSending.project.EmailOuterClass.APIResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.EmailSending.project.EmailOuterClass.APIResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.EmailSending.project.EmailOuterClass.APIResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.EmailSending.project.EmailOuterClass.APIResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code APIResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:APIResponse)
        com.EmailSending.project.EmailOuterClass.APIResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.EmailSending.project.EmailOuterClass.internal_static_APIResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.EmailSending.project.EmailOuterClass.internal_static_APIResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.EmailSending.project.EmailOuterClass.APIResponse.class, com.EmailSending.project.EmailOuterClass.APIResponse.Builder.class);
      }

      // Construct using com.EmailSending.project.EmailOuterClass.APIResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseMessage_ = "";

        messageCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.EmailSending.project.EmailOuterClass.internal_static_APIResponse_descriptor;
      }

      @java.lang.Override
      public com.EmailSending.project.EmailOuterClass.APIResponse getDefaultInstanceForType() {
        return com.EmailSending.project.EmailOuterClass.APIResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.EmailSending.project.EmailOuterClass.APIResponse build() {
        com.EmailSending.project.EmailOuterClass.APIResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.EmailSending.project.EmailOuterClass.APIResponse buildPartial() {
        com.EmailSending.project.EmailOuterClass.APIResponse result = new com.EmailSending.project.EmailOuterClass.APIResponse(this);
        result.responseMessage_ = responseMessage_;
        result.messageCode_ = messageCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.EmailSending.project.EmailOuterClass.APIResponse) {
          return mergeFrom((com.EmailSending.project.EmailOuterClass.APIResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.EmailSending.project.EmailOuterClass.APIResponse other) {
        if (other == com.EmailSending.project.EmailOuterClass.APIResponse.getDefaultInstance()) return this;
        if (!other.getResponseMessage().isEmpty()) {
          responseMessage_ = other.responseMessage_;
          onChanged();
        }
        if (other.getMessageCode() != 0) {
          setMessageCode(other.getMessageCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.EmailSending.project.EmailOuterClass.APIResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.EmailSending.project.EmailOuterClass.APIResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object responseMessage_ = "";
      /**
       * <code>string responseMessage = 1;</code>
       */
      public java.lang.String getResponseMessage() {
        java.lang.Object ref = responseMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseMessageBytes() {
        java.lang.Object ref = responseMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public Builder setResponseMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public Builder clearResponseMessage() {
        
        responseMessage_ = getDefaultInstance().getResponseMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public Builder setResponseMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseMessage_ = value;
        onChanged();
        return this;
      }

      private int messageCode_ ;
      /**
       * <code>int32 messageCode = 2;</code>
       */
      public int getMessageCode() {
        return messageCode_;
      }
      /**
       * <code>int32 messageCode = 2;</code>
       */
      public Builder setMessageCode(int value) {
        
        messageCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 messageCode = 2;</code>
       */
      public Builder clearMessageCode() {
        
        messageCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:APIResponse)
    }

    // @@protoc_insertion_point(class_scope:APIResponse)
    private static final com.EmailSending.project.EmailOuterClass.APIResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.EmailSending.project.EmailOuterClass.APIResponse();
    }

    public static com.EmailSending.project.EmailOuterClass.APIResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<APIResponse>
        PARSER = new com.google.protobuf.AbstractParser<APIResponse>() {
      @java.lang.Override
      public APIResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new APIResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<APIResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<APIResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.EmailSending.project.EmailOuterClass.APIResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Notifications_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Notifications_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APIResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013email.proto\"\277\001\n\rNotifications\022\027\n\017inter" +
      "vieweeName\030\001 \001(\t\022\027\n\017ReceiverEmailId\030\002 \001(" +
      "\t\022\021\n\tjob_title\030\003 \001(\t\022\021\n\tStartTime\030\004 \001(\t\022" +
      "\017\n\007EndTime\030\005 \001(\t\022\014\n\004Date\030\006 \001(\t\022\026\n\016Interv" +
      "iewrName\030\007 \001(\t\022\037\n\027meeting_invitation_lin" +
      "k\030\010 \001(\t\";\n\013APIResponse\022\027\n\017responseMessag" +
      "e\030\001 \001(\t\022\023\n\013messageCode\030\002 \001(\0052\263\001\n\005Email\0226" +
      "\n\026sendEmailOnSlotBooking\022\016.Notifications" +
      "\032\014.APIResponse\0225\n\025sendEmailOnSlotUpdate\022" +
      "\016.Notifications\032\014.APIResponse\022;\n\033sendEma" +
      "ilOnSlotcancellation\022\016.Notifications\032\014.A" +
      "PIResponseB\032\n\030com.EmailSending.projectb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Notifications_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Notifications_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Notifications_descriptor,
        new java.lang.String[] { "IntervieweeName", "ReceiverEmailId", "JobTitle", "StartTime", "EndTime", "Date", "InterviewrName", "MeetingInvitationLink", });
    internal_static_APIResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_APIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APIResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "MessageCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
