// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration.proto

package com.gl.registration;

public final class Registration {
  private Registration() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022registration.proto\022\014registration\032\raddU" +
      "ser.proto\032\020updateUser.proto\032\020deleteUser." +
      "proto\032\023getUserByMail.proto\032\031getUsersByTe" +
      "chStack.proto2\242\003\n\024registrationServices\022>" +
      "\n\007addUser\022\030.registration.addRequest\032\031.re" +
      "gistration.addResponse\022G\n\nupdateUser\022\033.r" +
      "egistration.updateRequest\032\034.registration" +
      ".updateResponse\022G\n\ndeleteUser\022\033.registra" +
      "tion.deleteRequest\032\034.registration.delete" +
      "Response\022X\n\rgetUserByMail\022\".registration" +
      ".getUserByMailRequest\032#.registration.get" +
      "UserByMailResponse\022^\n\023getUsersByTechStac" +
      "k\022\".registration.getUserByTechRequest\032#." +
      "registration.getUserByTechResponseB\027\n\023co" +
      "m.gl.registrationP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gl.grpc.AddUser.getDescriptor(),
          com.gl.grpc.UpdateUser.getDescriptor(),
          com.gl.grpc.DeleteUser.getDescriptor(),
          com.gl.grpc.GetUserByMail.getDescriptor(),
          com.gl.grpc.GetUsersByTechStack.getDescriptor(),
        }, assigner);
    com.gl.grpc.AddUser.getDescriptor();
    com.gl.grpc.UpdateUser.getDescriptor();
    com.gl.grpc.DeleteUser.getDescriptor();
    com.gl.grpc.GetUserByMail.getDescriptor();
    com.gl.grpc.GetUsersByTechStack.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
