// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addUser.proto

package com.gl.grpc;

public final class AddUser {
  private AddUser() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registration_addRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registration_addRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registration_addResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registration_addResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\raddUser.proto\022\014registration\"\214\001\n\naddReq" +
      "uest\022\020\n\010userName\030\001 \001(\t\022\017\n\007phoneNo\030\002 \001(\003\022" +
      "\017\n\007emailId\030\003 \001(\t\022\024\n\014userPassword\030\004 \001(\t\022\020" +
      "\n\010userRole\030\005 \001(\t\022\021\n\ttechStack\030\006 \001(\t\022\017\n\007j" +
      "obRole\030\007 \001(\t\"<\n\013addResponse\022\027\n\017responseM" +
      "essage\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005B\017\n\013co" +
      "m.gl.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_registration_addRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_registration_addRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registration_addRequest_descriptor,
        new java.lang.String[] { "UserName", "PhoneNo", "EmailId", "UserPassword", "UserRole", "TechStack", "JobRole", });
    internal_static_registration_addResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_registration_addResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registration_addResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
