// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: deleteUser.proto

package com.gl.grpc;

public interface deleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registration.deleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string emailId = 1;</code>
   */
  java.lang.String getEmailId();
  /**
   * <code>string emailId = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmailIdBytes();
}
