// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: getUsersByTechStack.proto

package com.gl.grpc;

public final class GetUsersByTechStack {
  private GetUsersByTechStack() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registration_getUserByTechRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registration_getUserByTechRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registration_getUserByTechResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registration_getUserByTechResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registration_userProfile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registration_userProfile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031getUsersByTechStack.proto\022\014registratio" +
      "n\")\n\024getUserByTechRequest\022\021\n\ttechStack\030\001" +
      " \001(\t\"L\n\025getUserByTechResponse\0223\n\020userPro" +
      "fileArray\030\001 \003(\0132\031.registration.userProfi" +
      "le\"\215\001\n\013userProfile\022\020\n\010userName\030\001 \001(\t\022\017\n\007" +
      "phoneNo\030\002 \001(\003\022\017\n\007emailId\030\003 \001(\t\022\024\n\014userPa" +
      "ssword\030\004 \001(\t\022\020\n\010userRole\030\005 \001(\t\022\021\n\ttechSt" +
      "ack\030\006 \001(\t\022\017\n\007jobRole\030\007 \001(\tB\017\n\013com.gl.grp" +
      "cP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_registration_getUserByTechRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_registration_getUserByTechRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registration_getUserByTechRequest_descriptor,
        new java.lang.String[] { "TechStack", });
    internal_static_registration_getUserByTechResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_registration_getUserByTechResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registration_getUserByTechResponse_descriptor,
        new java.lang.String[] { "UserProfileArray", });
    internal_static_registration_userProfile_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_registration_userProfile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registration_userProfile_descriptor,
        new java.lang.String[] { "UserName", "PhoneNo", "EmailId", "UserPassword", "UserRole", "TechStack", "JobRole", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
