// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: getUsersByTechStack.proto

package com.gl.grpc;

public interface getUserByTechResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registration.getUserByTechResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .registration.userProfile userProfileArray = 1;</code>
   */
  java.util.List<com.gl.grpc.userProfile> 
      getUserProfileArrayList();
  /**
   * <code>repeated .registration.userProfile userProfileArray = 1;</code>
   */
  com.gl.grpc.userProfile getUserProfileArray(int index);
  /**
   * <code>repeated .registration.userProfile userProfileArray = 1;</code>
   */
  int getUserProfileArrayCount();
  /**
   * <code>repeated .registration.userProfile userProfileArray = 1;</code>
   */
  java.util.List<? extends com.gl.grpc.userProfileOrBuilder> 
      getUserProfileArrayOrBuilderList();
  /**
   * <code>repeated .registration.userProfile userProfileArray = 1;</code>
   */
  com.gl.grpc.userProfileOrBuilder getUserProfileArrayOrBuilder(
      int index);
}
