// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: getUsersByTechStack.proto

package com.gl.grpc;

public interface getUserByTechRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registration.getUserByTechRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string techStack = 1;</code>
   */
  java.lang.String getTechStack();
  /**
   * <code>string techStack = 1;</code>
   */
  com.google.protobuf.ByteString
      getTechStackBytes();
}
