// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: getUserByMail.proto

package com.gl.grpc;

public final class GetUserByMail {
  private GetUserByMail() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registration_getUserByMailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registration_getUserByMailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registration_getUserByMailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registration_getUserByMailResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023getUserByMail.proto\022\014registration\"\'\n\024g" +
      "etUserByMailRequest\022\017\n\007emailId\030\001 \001(\t\"\227\001\n" +
      "\025getUserByMailResponse\022\020\n\010userName\030\001 \001(\t" +
      "\022\017\n\007phoneNo\030\002 \001(\003\022\017\n\007emailId\030\003 \001(\t\022\024\n\014us" +
      "erPassword\030\004 \001(\t\022\020\n\010userRole\030\005 \001(\t\022\021\n\tte" +
      "chStack\030\006 \001(\t\022\017\n\007jobRole\030\007 \001(\tB\017\n\013com.gl" +
      ".grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_registration_getUserByMailRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_registration_getUserByMailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registration_getUserByMailRequest_descriptor,
        new java.lang.String[] { "EmailId", });
    internal_static_registration_getUserByMailResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_registration_getUserByMailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registration_getUserByMailResponse_descriptor,
        new java.lang.String[] { "UserName", "PhoneNo", "EmailId", "UserPassword", "UserRole", "TechStack", "JobRole", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
