// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: getUserByMail.proto

package com.gl.grpc;

public interface getUserByMailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registration.getUserByMailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string emailId = 1;</code>
   */
  java.lang.String getEmailId();
  /**
   * <code>string emailId = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmailIdBytes();
}
