// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: updateUser.proto

package com.gl.grpc;

public final class UpdateUser {
  private UpdateUser() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registration_updateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registration_updateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registration_updateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registration_updateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020updateUser.proto\022\014registration\"\217\001\n\rupd" +
      "ateRequest\022\020\n\010userName\030\001 \001(\t\022\017\n\007phoneNo\030" +
      "\002 \001(\003\022\017\n\007emailId\030\003 \001(\t\022\024\n\014userPassword\030\004" +
      " \001(\t\022\020\n\010userRole\030\005 \001(\t\022\021\n\ttechStack\030\006 \001(" +
      "\t\022\017\n\007jobRole\030\007 \001(\t\"?\n\016updateResponse\022\027\n\017" +
      "responseMessage\030\001 \001(\t\022\024\n\014responseCode\030\002 " +
      "\001(\005B\017\n\013com.gl.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_registration_updateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_registration_updateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registration_updateRequest_descriptor,
        new java.lang.String[] { "UserName", "PhoneNo", "EmailId", "UserPassword", "UserRole", "TechStack", "JobRole", });
    internal_static_registration_updateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_registration_updateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registration_updateResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
