// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: updateUser.proto

package com.gl.grpc;

public interface updateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registration.updateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>int64 phoneNo = 2;</code>
   */
  long getPhoneNo();

  /**
   * <code>string emailId = 3;</code>
   */
  java.lang.String getEmailId();
  /**
   * <code>string emailId = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailIdBytes();

  /**
   * <code>string userPassword = 4;</code>
   */
  java.lang.String getUserPassword();
  /**
   * <code>string userPassword = 4;</code>
   */
  com.google.protobuf.ByteString
      getUserPasswordBytes();

  /**
   * <code>string userRole = 5;</code>
   */
  java.lang.String getUserRole();
  /**
   * <code>string userRole = 5;</code>
   */
  com.google.protobuf.ByteString
      getUserRoleBytes();

  /**
   * <code>string techStack = 6;</code>
   */
  java.lang.String getTechStack();
  /**
   * <code>string techStack = 6;</code>
   */
  com.google.protobuf.ByteString
      getTechStackBytes();

  /**
   * <code>string jobRole = 7;</code>
   */
  java.lang.String getJobRole();
  /**
   * <code>string jobRole = 7;</code>
   */
  com.google.protobuf.ByteString
      getJobRoleBytes();
}
